language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "graceshopper-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: old-town-node
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: JBvxj8t3YOaYB5HPWAMNxajBF62ZODA1PTLq8bzwxtwqVe/7BQB2VLgRe42/0Q6VoXNz41NoWh2pm30I4grXRG86cAciQFCZOkzx04RHQ9gCXO8vK/gfZKH1LwvsldYwNoHBK/2hYirgql0oyZ8XrOwLzEtuJqziy0ZfceYEXg94LWefvautPqps/mwyXheTxVjoECi2NP/OxaP/CuqLFB42pGhHBpXAzkNi4I/oZv7mWpGc/sLqwopOLTxaWQz242L8IZ+c25RZ9KX/BisTBksuNW+L5KRLBO311Wm6oOlnc/qugfWPtcwZS11KQILM466k7Ep2bI3c/Fnj6fNk9vuRETL7F7xNJv/MmOvH7Y5knAoSbnN7o26Db9R29UcPNnfNtgHNN4uKkQTpHToY8dl8GzRLCkerNwWZEQDMtO2dMkufVUSm9zTwKbjOE74ys92wzD+Y6cJW86bg0tzC3xx/V0OHvQHj5sCd0XDCRH7IwUoFCp+5ga4r3VhVbNwhAa224ajuWBymOdaAWfSG4utJcRCJbRK2zJ1bcHkP7lArF0ROsxIJ3mSMO10aprjKXlrQvnKSKhTFbau147cBUr7k5GoTfyZGCwLteucYx3OWYpimh34WFTCtwT54ehqjowW/1IcOD9HH1YsZaS4Paga9UUaNoLx/2NlpHQsid6w=
